<?php

namespace ctroc\demoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * familyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class familyRepository extends EntityRepository
{
}
