<?php

namespace ctroc\demoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * medical_infoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class medical_infoRepository extends EntityRepository
{
}
